### ISSUE TITLE
Output in .json

### ISSUE THREAD

**Issue by FranciscoHS** [SURFQuantum/yotse#20] opened 2023-07-27 11:37 UTC
The script i am using yotse with outputs .json files. The following docstring fragment, extracted from the `SystemSetup` method of `pre.py` implies that this is supported:

    output_extension : str (optional)
        Extension of the output files to be picked up by the analysis_script, e.g 'csv' or 'json'. Defaults to 'csv'.
        
However, running my code gives me the following error:

Traceback (most recent call last):
  File "/gpfs/home5/fsilva/project_rl_quantum/experiments/purify_entangle_discard/simplified/potential_shaped_reward/0/yotse_rl.py", line 74, in <module>
    main()
  File "/gpfs/home5/fsilva/project_rl_quantum/experiments/purify_entangle_discard/simplified/potential_shaped_reward/0/yotse_rl.py", line 67, in main
    rl_example.run(step=0)
  File "//home/fsilva/project_rl_quantum/yotse/yotse/run.py", line 377, in run
    super().run(step, evolutionary_point_generation)
  File "//home/fsilva/project_rl_quantum/yotse/yotse/run.py", line 126, in run
    data = self.collect_data()
  File "//home/fsilva/project_rl_quantum/yotse/yotse/run.py", line 201, in collect_data
    data = file_list_to_single_df(files)
  File "//home/fsilva/project_rl_quantum/yotse/yotse/run.py", line 79, in file_list_to_single_df
    dfs = [pandas.read_csv(file, delimiter=' ') for file in files]
  File "//home/fsilva/project_rl_quantum/yotse/yotse/run.py", line 79, in <listcomp>
    dfs = [pandas.read_csv(file, delimiter=' ') for file in files]
  File "/gpfs/home5/fsilva/rlquantumenv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/gpfs/home5/fsilva/rlquantumenv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/gpfs/home5/fsilva/rlquantumenv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/gpfs/home5/fsilva/rlquantumenv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1254, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/gpfs/home5/fsilva/rlquantumenv/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 805, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 6 fields in line 3, saw 10

After having a look at `run.py`, I believe that yotse does not actually (yet) support output in a format other than .csv. Are there plans to change this? Here is my yotse script:

```
import os
import shutil
from yotse.pre import Experiment, SystemSetup, Parameter
from yotse.run import Executor


def dumb_dist(min_value, max_value, number_points):
    return [0.]


def rl_input():
    rl_experiment = Experiment(
        experiment_name="EntangleMaster",
        system_setup=SystemSetup(
            source_directory=os.getcwd(),
            program_name="entangle_master_runscript.py",
            command_line_arguments={"--alpha": 0.1,
                                    "--elementary_link_fidelity": 0.88,
                                    "--n_trials": 10,
                                    "--single_gen_action": True,
                                    "--target_fidelity": 0.9,
                                    "--eta": 0.1,
                                    "--n_coherence": 10},
            # analysis_script="analyse_function_output.py",
            executor="python",
            output_dir_name="output",
            venv="~/rlquantumenv",
            num_nodes=1,
            alloc_time="04:00:00",
            slurm_args=["--exclusive"],
            modules=["2021", "Python/3.9.5-GCCcore-10.3.0"],
            output_extension="json"
        ),
        parameters=[
            Parameter(
                name="gamma",
                param_range=[0., 1.],
                constraints={'low': 0., 'high': 1.},
                number_points=1,
                distribution="custom",
                param_type="continuous",
                custom_distribution=dumb_dist,
            )
        ]
    )

    return rl_experiment


def remove_files_after_run():
    # remove files and directories
    dirs = [f for f in os.listdir(os.getcwd()) if (f.startswith(".qcg"))]
    for d in dirs:
        shutil.rmtree(os.path.join(os.getcwd(), d))


def main():
    def cost_function(f):
        return f

    experiment = rl_input()
    experiment.cost_function = cost_function
    rl_example = Executor(experiment=experiment)

    experiment.parse_slurm_arg('qiaopt_rl.py')

    rl_example.run(step=0)

    # clean up
    remove_files_after_run()


if __name__ == "__main__":
    main()
```

The script that it calls (`entangle_master_runscript.py`) makes calls to a bunch of repositories making it a bit of a hassle to run. I can make a minimal example if that's helpful.

**Comment by dmark04** [comment] 2023-08-07 11:28
Hey @FranciscoHS, thanks for reporting this. No need to make a minimal example (for now), I think it's quite clear what the issue is indeed. 
In the script you supplied you commented out the `analysis_script` parameter, is that intentional?
Just to make sure I understand could you very briefly outline the behavior you would like to achieve? (like: you run your script, each job outputs a .json, you want yotse to combine this, or each job already has some analysis in it and you just use yotse to schedule the jobs)

**Comment by dmark04** [comment] 2023-08-07 12:36
I added a few changes in the branch connected to this issue.
@FranciscoHS could you check if this fixes your issue? Then I will add some proper tests for the entire functionality.

Also out of curiosity: Do you foresee using any other file extensions in your work? Then I could add support for those ones as well (currently only csv, json and pickle).

**Comment by dmark04** [comment] 2023-08-16 12:48
Alright sounds good.

Then last question: Would it be useful to have a way to not combine output at all?

**Comment by FranciscoHS** [comment] 2023-08-17 14:51
I would say yes, but with very very low priority.

**Comment by dmark04** [comment] 2023-10-24 09:17
Support for pickle and json output  is now resolved in https://github.com/SURFQuantum/yotse/pull/26

**Closed by dmark04** 2023-10-24 09:17 UTC
Labels: bug
